const lang = {
		        en: {
		             m_tab1: "Text Message"
		            ,m_tab2: "Friends Talk"
		            ,m_tab3: "Alert Talk"
		            ,m_scheduled: "Scheduled Message"
		            ,m_result: "Sent Result"
		            ,m_choose: "Choose the tab to create message"
		            ,f_template: "Template"
		            ,f_templateView: "View Template"
		            ,f_number: "Sending Number"
		            ,f_scheduleDate: "Schedule Date"
		            ,f_selectDate: "Select Date"
		            ,f_sendAtNightStatus: "Force to Send even at Night"
		            ,f_sendAtNightWarn: "※ Need to obtain the consent from the addressee to send at Night"
		            ,f_adStatus: "Advertising Status"
		            ,f_informative: "Informative"
		            ,f_advertising: "Advertising"
		            ,f_080Number: "080 Block Number"
		            ,f_adPhrase: "Failback Phrase"
		            ,f_customerInfo: "Customer Information"
		            ,f_enterMessage: "Enter the message"
				    ,f_imgUpload: "Image Upload"
				    ,f_selectFile: "Select a file"	
				    ,f_selectBtn: "Button Select"
				    ,f_btnType: "Button Type"
				    ,f_btnName: "Button Name"	
				    ,f_btnLink: "Button Link"	
				    ,f_profileKey: "Profile Key"
					,f_imgUrl: "Image URL"
					,f_imgName: "Image Name"
					,f_imgThumbnail: "Thumbnail"
					,f_imgView: "View Images"
					,f_imgUploadUrl: "Image Link URL"
					,f_sendFtalkMessage: "Send ‘Friends Talk’ Message"
					,f_sendAtalkMessage: "Send ‘Alert Talk’ Message"
					,f_viewTemplate: "View Template"
					,f_search: "Search"
					,f_templateName: "Template Name"
					,f_total: "Total"
					,f_list: "List"
					,f_type: "Type"
					,f_registeredDate: "Registered Date"
					,f_add: "Add"
					,f_delete: "Delete"
					,f_addTemplate: "Add Template"
					,f_journeyVersionActivity: "Journey+Version+Activity"
					,f_journeyName: "Journey Name"
					,f_version: "Version"
					,f_activityName: "Activity Name"
					,f_scheduledDate: "Scheduled Date"
					,f_noOfSent: "No. of Sent"
					,f_status: "Status"
					,f_note: "Note"
					,f_sentCancel: "Cancel Send"
					,f_totalSent: "Total Sent"
					,f_totalCost: "Total Cost"		
					,f_membershipLevel: "Membership Level"
					,f_sending: "Sending"
					,f_sent: "Sent"
					,f_success: "Success"
					,f_cost: "Cost"
					,f_friendsTalkButton: "Friends Talk Button"
					,f_sendingStatus: "Sending Status"
					,f_immediate: "Immediate"
					,f_schedule: "Schedule"
					,f_save: "Add"
					,f_cancel: "Cancel"
					,f_loading: "Loading"
					,f_close: "Close"
					,f_hltType: "Highlight Type"
					,f_hltMainTitle: "Highlight Title"
					,f_hltSubTitle: "Highlight Sub Title"
					,f_status_wait: "Waiting"
					,f_status_cancel: "Canceled"
					,f_kbo_web_link: "Web Link"
					,f_kbo_web_link_pc_optional: "PC(Optional)"
					,f_kbo_web_link_mobile_required: "Mobile(Required)"
					,f_kbo_app_link: "App Link"
					,f_kbo_app_link_android_required: "Android(Required)"
					,f_kbo_app_link_ios_required: "IOS(Required)"
					,f_kbo_bot_keyword: "Bot Keyword"
					,f_kbo_msg_forward: "FWD Msg"
					,f_kbo_delivery_check: "Delivery Check"
					,a_1:"Save the Journey."
					,a_2:"Unverified Marketing Cloud."
					,a_3:"Select sending number."
					,a_4:"Select Friends Talk template."
					,a_5:"Enter the message title."
					,a_6:"Enter the message."
					,a_7:"Data Extension field is required for personalization field in the message."
					,a_8:"Select the date."
					,a_9:"Enter in 24-hour notation hh:mm."
					,a_10:"Enter the scheduled time after 30 minutes."
					,a_11:"Select the Data Extension Object."
					,a_12:"Select the template to delete."
					,a_13:"Maximum number of button is 5."
					,a_14:"Message cannot exceed 2,000 byte."
					,a_15:"Saved successfully"
					,a_16:"Select jpg file only."
					,a_17:"Only 100KB or less can be sent."
					,a_18:"Failed to save"
					,a_19:"Enter the template name."
					,a_20:"Select the profile key."
					,a_21:"Enter the button name and button link for added button."
					,a_22:"Select button type for added button."
					,a_23:"Verification Failed. Please refresh the page and retry."
					,a_24:"Are you sure you want to delete it?"
					,a_25:"Cancellation Successfully"
					,a_26:"You can only cancel the reserved messages until 5 minutes before sending."
					,a_27:"Deleted Successfully"
					,a_28:"You can only send a message between 08:00 and 20:00"
					,a_29:"A fine of up to thirty million won will be imposed on a person that not only who sends advertising information for profit by using an electronic transmission medium during the time between 9:00pm and 8:00am of the following day without obtaining express prior consent from the addressee of such information, but also who commits such acts.<br>※ ACT ON PROMOTION OF INFORMATION AND COMMUNICATIONS NETWORK UTILIZATION AND INFORMATION PROTECTION, ETC. Article 76 (1) 7"
		        	,a_30:"Data Extension field is required for personalization field in the Button Link."
		        	,a_31:"Button Link MUST include \'http://\' or \'https://\'."
		        	,a_32:"080 Block Number is Mandatory for Advertising Message."
		        	,a_33:"Friends Talk Text Message cannot exceed 1,000 Characters"
		        	,a_34:"Friends Talk IMG Message cannot exceed 400 Characters"
		        },       
		        ko: {
		        	 m_tab1: "문자메세지"
		            ,m_tab2: "친구톡"
		            ,m_tab3: "알림톡"
		            ,m_scheduled: "발송예약조회"
		            ,m_result: "발송결과조회"
		            ,m_choose: "메시지 만들기 탭을 선택하세요."
		            ,f_template: "템플릿"
		            ,f_templateView: "템플릿 조회"
		            ,f_number: "발신번호"
		            ,f_scheduleDate: "예약일시"
		            ,f_selectDate: "날짜선택"
		            ,f_sendAtNightStatus: "야간발송"
		            ,f_sendAtNightWarn: "※ 야간시간 광고성 정보 전송은 별도 동의 필요함"
		            ,f_adStatus: "광고성 여부"
		            ,f_informative: "정보성"
		            ,f_advertising: "광고성"
		            ,f_080Number: "080수신거부번호"
		            ,f_adPhrase: "failback문구"
		            ,f_customerInfo: "고객정보"
		            ,f_enterMessage: "메시지 내용을 입력해 주세요."
				    ,f_imgUpload: "이미지 업로드"
				    ,f_selectFile: "파일선택"
				    ,f_selectBtn: "버튼 선택"
				    ,f_btnType: "버튼타입"
				    ,f_btnName: "버튼이름"	
				    ,f_btnLink: "버튼링크"	
				    ,f_profileKey: "프로파일 Key"
					,f_imgUrl: "이미지 URL"
					,f_imgName: "이미지명"
					,f_imgThumbnail: "이미지썸네일"
					,f_imgView: "이미지 조회"
					,f_imgUploadUrl: "이미지 링크 URL"
					,f_sendFtalkMessage: "친구톡 메세지 보내기"
					,f_sendAtalkMessage: "알림톡 메세지 보내기"
					,f_viewTemplate: "템플릿 조회"
					,f_search: "검색"
					,f_templateName: "템플릿명"
					,f_total: "전체"
					,f_list: "목록"
					,f_type: "타입"
					,f_registeredDate: "등록일자"
					,f_add: "추가"
					,f_delete: "삭제"
					,f_addTemplate: "템플릿 등록"
					,f_journeyVersionActivity: "저니명+버전+액티비티명"
					,f_journeyName: "저니명"
					,f_version: "버전"
					,f_activityName: "액티비티명"
					,f_scheduledDate: "발송예약일시"
					,f_noOfSent: "발송건수"
					,f_status: "상태"
					,f_note: "비고"
					,f_sentCancel: "발송취소"
					,f_totalSent: "전체발송건수"
					,f_totalCost: "전체발송비용"					
					,f_membershipLevel: "회원레벨"
					,f_sending: "발송시작"
					,f_sent: "발송종료"
					,f_success: "성공건수"
					,f_cost: "발송비용"
					,f_friendsTalkButton: "친구톡 버튼"
					,f_sendingStatus: "발송구분"
					,f_immediate: "즉시발송"
					,f_schedule: "예약발송"
					,f_save: "등록"
					,f_cancel: "취소"
					,f_loading: "인증 중"
					,f_close: "닫기"
					,f_hltType: "강조타입"
					,f_hltMainTitle: "강조제목"
					,f_hltSubTitle: "강조보조문구"
					,f_status_wait: "대기"
					,f_status_cancel: "취소"
					,f_kbo_web_link: "웹링크"
					,f_kbo_web_link_pc_optional: "PC(선택)"
					,f_kbo_web_link_mobile_required: "Mobile(필수)"
					,f_kbo_app_link: "앱링크"
					,f_kbo_app_link_android_required: "Android(필수)"
					,f_kbo_app_link_ios_required: "IOS(필수)"
					,f_kbo_bot_keyword: "봇키워드"
					,f_kbo_msg_forward: "메시지전달"
					,f_kbo_delivery_check: "배송조회"
					,a_1:"Journey를 Save 해주시기 바랍니다."
					,a_2:"인증 되지 않은 Markting Cloud 입니다."
					,a_3:"발신번호를 선택해주세요."
					,a_4:"친구톡 템플릿을 선택해주세요."
					,a_5:"메시지 제목을 입력해주세요."
					,a_6:"메시지 내용을 입력해주세요."
					,a_7:"메시지 내용의 개인화필드는 Data Extension 필드 선언이 필수입니다."
					,a_8:"날짜를 선택해 주시기 바랍니다."
					,a_9:"24시간 xx:xx 형식으로 입력해 주시기 바랍니다."
					,a_10:"문자 예약 시간을 30분 후로 입력해 주시기 바랍니다."
					,a_11:"Data Extension Object 를 선택해 주세요."
					,a_12:"삭제할 템플릿을 선택해주세요."
					,a_13:"버튼은 5개까지 입니다."
					,a_14:"메세지는 최대 2000 byte를 초과할 수 없습니다."
					,a_15:"저장 성공"
					,a_16:"jpg 파일만 선택해 주시기 바랍니다."
					,a_17:"100KB 이하만 전송가능 합니다."
					,a_18:"파일 저장실패"
					,a_19:"템플릿명을 입력해 주세요."
					,a_20:"프로파일 Key를 선택해 주세요."
					,a_21:"추가된 버튼의 버튼명과 버튼링크를 작성해 주시기 바랍니다."
					,a_22:"추가된 버튼의 버튼타입을 선택해 주시기 바랍니다."
					,a_23:"인증실패 잠시 후 시도해 주시거나 새로 고침 해주시기 바랍니다."
					,a_24:"삭제 하시겠습니까?"
					,a_25:"취소 성공"
					,a_26:"예약발송은 발송 5분 전까지만 취소 가능합니다."
					,a_27:"삭제 성공"
					,a_28:"문자는 08시부터 20시까지만 발송 가능합니다."
					,a_29:"야간시간 광고성 정보 전송에 대한 별도의 동의를 받지 않고 오후 9시부터 그 다음 날 오전 8시 사이에 광고성 정보를 전송한 자 뿐만 아니라 그러한 행위를 하도록 한 자의 경우에는 3천만원 이하의 과태료가 부과됩니다.<br>※ 정보통신망법 제76조 제1항 제7호"
		        	,a_30:"버튼링크의 개인화필드는 Data Extension 필드 선언이 필수입니다."
		        	,a_31:"버튼링크의 URL주소는 반드시 \'http://\' 혹은 \'https://\' 를 포함하여야 합니다."
		        	,a_32:"광고성 메시지는 080수신거부번호가 필수입니다."
		        	,a_33:"친구톡텍스트는 최대 1000자를 초과할 수 없습니다."
		        	,a_34:"친구톡이미지는 최대 400자를 초과할 수 없습니다."
		        }
	  }

const langKeySet = Object.keys(lang);

function render(locale) {		
	const $lang = document.querySelectorAll("[data-lang], [data-lang-placeholder]");
    $lang.forEach(el => {
		var code = el.dataset.lang
		if (typeof $(el).attr('data-lang-placeholder') !== typeof undefined && $(el).attr('data-lang-placeholder') !== false) {
			code = el.dataset.langPlaceholder;
			$(el).attr('placeholder', lang[locale][code]);
		}
		
		el.innerHTML = el.innerHTML.replace(code, lang[locale][code]).replace(/\[|\]/g, '');
		$.each(langKeySet, function() {
			el.innerHTML = el.innerHTML.replace(lang[this][code], lang[locale][code]).replace(/\[|\]/g, '');
		});
    });

	if (window.createPicker) {
		window.createPicker(locale);
	}
}
